# Server config
server:
  port: 9000

# Kafka config
spring:
  kafka:
    producer:
      bootstrap-servers: omnibus-01.srvs.cloudkafka.com:9094,omnibus-02.srvs.cloudkafka.com:9094,omnibus-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security:
           protocol: SASL_SSL
        sasl:
          mechanism: SCRAM-SHA-256
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="oo6eeuc2" password="mob12Cn5pNnyP54cshOTm63gq31bD6ie";
cloudkarafka:
  topic: oo6eeuc2-default

# Logging config
logging:
  level:
    root: "info"
    org.springframework.web: "debug"
    org.hibernate: "error"

# Security config
security:
  signing-key: YmZlYTc4M2RzZmdjOWI5ZHNmZDo4YTkwMzBmYmNhODlhNWIyYzI4ZTkyZjEzNDUwYmI3NzgyNGI1YWQx
  jwt:
    client-id: bfea783dsfgc9b9dsfd
    client-secret: 8a9030fbca89a5b2c28e92f13450bb77824b5ad1
    grant-type: authorization_code # consider password?
    resource-ids: 2ed0eg9e-8338-4ed7-b101-38ae561e6ct6
 